### Dictoinary 

#### Has key value pair stucture  
#### key is unique
#### values can be duplicated
#### values can be retrive using key 
#### key cannot be retrive using value

In [3]:
saple_dict={1:"apple",2:35.4,3:"data",2:"every",6:35.4,7:35.4,2:"hi"}
saple_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 35.4}

In [4]:
saple_dict[3]

'data'

In [5]:
saple_dict["apple"]

KeyError: 'apple'

In [6]:
saple_dict[7]

35.4

In [7]:
saple_dict[7]=100

In [8]:
saple_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 100}

In [9]:
saple_dict[10]="Business"

In [10]:
saple_dict

{1: 'apple', 2: 'hi', 3: 'data', 6: 35.4, 7: 100, 10: 'Business'}

### Numpy : Packages for Multidimensoinal array

In [11]:
import numpy as np

In [12]:
sample_list=[6,7,9]
np.array(sample_list)

array([6, 7, 9])

In [13]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [15]:
list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Shift+tab when you forgat something

In [16]:
np.arange(5,65)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64])

In [19]:
np.arange(1,30,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

#### create whole number upto 50
#### 0,1,2,....50

In [34]:
np.arange(51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.ones(100,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [24]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [30]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [27]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [28]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [44]:
np.eye(10,int)

TypeError: 'type' object cannot be interpreted as an integer

In [45]:
np.eye(10,dtype=int)###np.eye((10),dtype=int)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [29]:
np.random.rand(2,4)

array([[0.49252444, 0.17229827, 0.68524635, 0.15792974],
       [0.85307516, 0.17224441, 0.89896101, 0.88128229]])

In [46]:
np.random.rand(3,5)

array([[0.64054829, 0.56539599, 0.30167458, 0.98530403, 0.33767686],
       [0.52505462, 0.99272994, 0.78049126, 0.93107756, 0.09499171],
       [0.34661163, 0.91127449, 0.74989647, 0.84658368, 0.39837769]])

In [47]:
arr=np.random.randn(2,4)
arr

array([[-0.18628135,  0.91937519, -1.26499204,  0.66858068],
       [ 0.25594927, -1.31267946,  0.03395134,  0.59797657]])

In [50]:
  np.random.randint(2,10)

8

In [49]:
np.random.randint(20,56,100)

array([54, 51, 48, 38, 31, 46, 36, 38, 25, 50, 43, 42, 36, 23, 23, 38, 33,
       34, 54, 29, 22, 51, 54, 30, 39, 52, 30, 40, 52, 29, 33, 40, 22, 52,
       41, 42, 23, 55, 39, 47, 28, 45, 55, 26, 25, 22, 51, 40, 41, 31, 40,
       36, 40, 55, 45, 29, 34, 53, 20, 35, 55, 55, 31, 30, 27, 39, 28, 25,
       44, 33, 49, 33, 28, 43, 51, 49, 29, 40, 44, 46, 26, 35, 41, 34, 20,
       24, 49, 24, 51, 21, 31, 28, 38, 22, 37, 21, 44, 46, 43, 49])

In [51]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
rand_array=np.random.randint(0,100,20)
rand_array

array([93, 92, 84, 45,  4, 22, 17, 60, 70,  0, 12, 67, 76, 22, 72, 21, 81,
       10, 73, 24])

In [57]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [62]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [63]:
sample_array.reshape(5,9)

ValueError: cannot reshape array of size 30 into shape (5,9)

In [58]:
rand_array.min()

0

In [59]:
rand_array.max()

93

In [60]:
rand_array.argmin()

9

In [61]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [65]:
rand_array.argmax()

0

In [67]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
a=np.random.rand(2,3)
a

array([[0.70492615, 0.01144391, 0.06224456],
       [0.55834005, 0.06542777, 0.88303524]])

In [71]:
a.T

array([[0.70492615, 0.55834005],
       [0.01144391, 0.06542777],
       [0.06224456, 0.88303524]])

In [75]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [76]:
sample_array[8]

18

In [77]:
sample_array[2:5]

array([12, 13, 14])

In [79]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [80]:
sample_array=np.arange(10,21)

In [81]:
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [82]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [84]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [85]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Diamensoin Array

In [86]:
import numpy as np

In [87]:
sample_matrix=np.array(([50,20,1,23],[23,24,21,33],[56,76,24,7]))

In [88]:
sample_matrix

array([[50, 20,  1, 23],
       [23, 24, 21, 33],
       [56, 76, 24,  7]])

In [89]:
sample_matrix[0,2]

1

In [91]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [92]:
sample_matrix[2]

array([56, 76, 24,  7])

In [96]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [97]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

### Selectoin Techniques

In [94]:
sample_array=np.arange(1,20)

In [95]:
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [98]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [99]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [100]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [101]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [102]:
np.max(sample_array)

19

In [103]:
np.min(sample_array)

1

In [104]:
np.argmin(sample_array)

0

In [105]:
np.argmax(sample_array)

18

In [108]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [109]:
np.std(sample_array)

5.477225575051661

In [110]:
np.var(sample_array)

30.0

In [111]:
np.mean(sample_array)

10.0

In [112]:
array=np.random.randn(3,4)

In [113]:
array

array([[ 1.98434836, -0.13542849,  0.16703515, -1.67619072],
       [ 0.83576715, -0.98526973, -0.55097324,  1.65016581],
       [ 2.14568176, -0.4205986 ,  0.76427793, -2.00271805]])

In [115]:
np.round(array,decimals=2)

array([[ 1.98, -0.14,  0.17, -1.68],
       [ 0.84, -0.99, -0.55,  1.65],
       [ 2.15, -0.42,  0.76, -2.  ]])

In [116]:
sport=np.array(['golf','cricket','football','cricket'])

In [117]:
sport

array(['golf', 'cricket', 'football', 'cricket'], dtype='<U8')

In [118]:
np.unique(sport)

array(['cricket', 'football', 'golf'], dtype='<U8')

 ### Pandas

In [120]:
import pandas as pd

In [121]:
import numpy as np

### pandas Series and Data Frame

#### Series 
##### 1. Form of sequentially one- dimensoinal arrrays
##### 2. All element one data type 
##### 3. Can be created from lists ,tuplesand array

#### Data Frame 
#### two dimension data structure that can store various types of data 

In [122]:
import pandas as pd

In [123]:
import numpy as np

In [125]:
pd.Series(["M","F","M","M","F"])

0    M
1    F
2    M
3    M
4    F
dtype: object

In [126]:
pd.Series(np.array(["M","F","M","M","F"]))

0    M
1    F
2    M
3    M
4    F
dtype: object

In [127]:
gen=pd.Series(np.array(["M","F","M","M","F"]))

In [128]:
gen

0    M
1    F
2    M
3    M
4    F
dtype: object

In [129]:
type(gen)

pandas.core.series.Series

In [130]:
dic={"a":1,"b":2,3:"c",4:15}

In [131]:
dic

{'a': 1, 'b': 2, 3: 'c', 4: 15}

In [134]:
dic_1=pd.Series(dic)

In [133]:
type(dic)

dict

In [135]:
type(dic_1)

pandas.core.series.Series

In [136]:
dic_1.index

Index(['a', 'b', 3, 4], dtype='object')

In [137]:
dic_1.values

array([1, 2, 'c', 15], dtype=object)

In [138]:
list_1=["2023-01-16",17.26,"murari",1000,True]

In [139]:
list_1

['2023-01-16', 17.26, 'murari', 1000, True]

In [140]:
pd.Series(list_1)

0    2023-01-16
1         17.26
2        murari
3          1000
4          True
dtype: object

In [141]:
ser=pd.Series(list_1)

In [142]:
ser.index

RangeIndex(start=0, stop=5, step=1)

In [147]:
df=pd.DataFrame({"Name":["murari","prema","Allen"],"Age":[21,22,34],"Sex":["F","F","M"]})

In [148]:
df

Name  Age Sex
0  murari   21   F
1   prema   22   F
2   Allen   34   M

In [150]:
df["Age"]

0    21
1    22
2    34
Name: Age, dtype: int64

In [152]:
type(df["Age"])

pandas.core.series.Series

In [153]:
df["Age"][0]

21

In [154]:
df.columns

Index(['Name', 'Age', 'Sex'], dtype='object')

In [155]:
df[0]

KeyError: 0

In [156]:
df["Name"][0]

'murari'

In [160]:
ser1=pd.Series([0,1,2,3,4],index=[0,1,2,2,3])
ser2=pd.Series([0,1,2,3,4],index=[1,2,3,4,5])

In [161]:
ser1

0    0
1    1
2    2
2    3
3    4
dtype: int64

In [162]:
ser2

1    0
2    1
3    2
4    3
5    4
dtype: int64

In [163]:
ser1+ser2

0    NaN
1    1.0
2    3.0
2    4.0
3    6.0
4    NaN
5    NaN
dtype: float64

In [164]:
ser1=pd.Series(["cricket","football","basketball"],index=[0,1,2])
ser2=pd.Series(["cricket","football","basketball"],index=[11,12,13])

In [165]:
ser1+ser2

0     NaN
1     NaN
2     NaN
11    NaN
12    NaN
13    NaN
dtype: object

In [178]:
ser1=pd.Series([0,1,2],index=["cricket","football","baseball"])
ser2=pd.Series([11,12,13],index=["cricket","football","basketball"])

In [179]:
ser1

cricket     0
football    1
baseball    2
dtype: int64

In [173]:
ser2

cricket       11
football      12
basketball    13
dtype: int64

In [180]:
ser1+ser2

baseball       NaN
basketball     NaN
cricket       11.0
football      13.0
dtype: float64

In [181]:
ser1*ser2

baseball       NaN
basketball     NaN
cricket        0.0
football      12.0
dtype: float64

In [182]:
ser1.sum()

3

In [183]:
ser2.sum()

36

In [184]:
ser1.mean()

1.0

In [186]:
ser1.median()

1.0

In [188]:
ser1.mode()

0    0
1    1
2    2
dtype: int64

In [189]:
ser1.std()

1.0

In [190]:
ser1.max()

2

In [191]:
ser2.max()

13

In [192]:
ser1.min()

0

In [193]:
ser1.var()

1.0

In [194]:
ser1

cricket     0
football    1
baseball    2
dtype: int64

In [195]:
ser1=pd.Series([50,1,22],index=["cricket","football","baseball"])
ser2=pd.Series([11,12,13],index=["cricket","football","basketball"])

In [196]:
ser1

cricket     50
football     1
baseball    22
dtype: int64

In [198]:
ser1.sort_values()

football     1
baseball    22
cricket     50
dtype: int64

In [199]:
ser3=pd.Series([11,12,13],name="ram")

In [200]:
plus_10=lambda x:x+10

In [201]:
plus_10(5)

15

In [202]:
ser3.apply(lambda x:x+10)

0    21
1    22
2    23
Name: ram, dtype: int64

In [203]:
ser3.apply(lambda x:x*10)

0    110
1    120
2    130
Name: ram, dtype: int64

In [204]:
ser3.apply(lambda x:x/10)

0    1.1
1    1.2
2    1.3
Name: ram, dtype: float64

In [206]:
import pandas as pd

In [207]:
 df=pd.read_csv("Cust_Spend_Data.csv")

In [208]:
df

Cust_ID Name  Avg_Mthly_Spend  No_Of_Visits  Apparel_Items  FnV_Items  \
0        1    A            10000             2              1          1   
1        2    B             7000             3              0         10   
2        3    C             7000             7              1          3   
3        4    D             6500             5              1          1   
4        5    E             6000             6              0         12   
5        6    F             4000             3              0          1   
6        7    G             2500             5              0         11   
7        8    H             2500             3              0          1   
8        9    I             2000             2              0          2   
9       10    J             1000             4              0          1   

   Staples_Items  
0              0  
1              9  
2              4  
3              4  
4              3  
5              8  
6              2  
7              1  
8              2  
9              7

In [209]:
df.head()

Cust_ID Name  Avg_Mthly_Spend  No_Of_Visits  Apparel_Items  FnV_Items  \
0        1    A            10000             2              1          1   
1        2    B             7000             3              0         10   
2        3    C             7000             7              1          3   
3        4    D             6500             5              1          1   
4        5    E             6000             6              0         12   

   Staples_Items  
0              0  
1              9  
2              4  
3              4  
4              3

In [210]:
columns=["id","name","avg","visits","apparel","items","staples"]
df=pd.read_csv("Cust_Spend_Data.csv",names=columns)

In [211]:
df

id  name              avg        visits        apparel      items  \
0   Cust_ID  Name  Avg_Mthly_Spend  No_Of_Visits  Apparel_Items  FnV_Items   
1         1     A            10000             2              1          1   
2         2     B             7000             3              0         10   
3         3     C             7000             7              1          3   
4         4     D             6500             5              1          1   
5         5     E             6000             6              0         12   
6         6     F             4000             3              0          1   
7         7     G             2500             5              0         11   
8         8     H             2500             3              0          1   
9         9     I             2000             2              0          2   
10       10     J             1000             4              0          1   

          staples  
0   Staples_Items  
1               0  
2               9  
3               4  
4               4  
5               3  
6               8  
7               2  
8               1  
9               2  
10              7

In [213]:
df.tail()

id name   avg visits apparel items staples
6    6    F  4000      3       0     1       8
7    7    G  2500      5       0    11       2
8    8    H  2500      3       0     1       1
9    9    I  2000      2       0     2       2
10  10    J  1000      4       0     1       7

In [216]:
df.sample()

id name   avg visits apparel items staples
7  7    G  2500      5       0    11       2

In [217]:
df.sample(2)

id name   avg visits apparel items staples
10  10    J  1000      4       0     1       7
5    5    E  6000      6       0    12       3

In [218]:
df.columns=["a","b","c","d","e","f","g"]

In [219]:
df

a     b                c             d              e          f  \
0   Cust_ID  Name  Avg_Mthly_Spend  No_Of_Visits  Apparel_Items  FnV_Items   
1         1     A            10000             2              1          1   
2         2     B             7000             3              0         10   
3         3     C             7000             7              1          3   
4         4     D             6500             5              1          1   
5         5     E             6000             6              0         12   
6         6     F             4000             3              0          1   
7         7     G             2500             5              0         11   
8         8     H             2500             3              0          1   
9         9     I             2000             2              0          2   
10       10     J             1000             4              0          1   

                g  
0   Staples_Items  
1               0  
2               9  
3               4  
4               4  
5               3  
6               8  
7               2  
8               1  
9               2  
10              7

In [220]:
df.a

0     Cust_ID
1           1
2           2
3           3
4           4
5           5
6           6
7           7
8           8
9           9
10         10
Name: a, dtype: object

In [223]:
df["a"]

0     Cust_ID
1           1
2           2
3           3
4           4
5           5
6           6
7           7
8           8
9           9
10         10
Name: a, dtype: object

In [225]:
df[["a","b"]]

a     b
0   Cust_ID  Name
1         1     A
2         2     B
3         3     C
4         4     D
5         5     E
6         6     F
7         7     G
8         8     H
9         9     I
10       10     J

In [227]:
df=pd.DataFrame([["murari",23,"male"],["latha",23,"female"]],columns=["name","Age","Sex"])

In [228]:
df

name  Age     Sex
0  murari   23    male
1   latha   23  female

In [229]:
df.index=["name1","name2"]

In [230]:
df

name  Age     Sex
name1  murari   23    male
name2   latha   23  female

In [231]:
df.index

Index(['name1', 'name2'], dtype='object')

In [232]:
df.rename(index={"name1":"name_1"})

name  Age     Sex
name_1  murari   23    male
name2    latha   23  female

In [233]:
df

name  Age     Sex
name1  murari   23    male
name2   latha   23  female

In [236]:
df.rename(index={"name1":"name_1"},inplace=True) #for orinal data change

In [235]:
df

name  Age     Sex
name_1  murari   23    male
name2    latha   23  female

In [238]:
df.rename(columns={"name":"names"},inplace=True)

In [239]:
df

names  Age     Sex
name_1  murari   23    male
name2    latha   23  female

In [244]:
scores={"math":[70,78,79],"eng":[56,67,66],"evg":[45,87,98]}
scores

{'math': [70, 78, 79], 'eng': [56, 67, 66], 'evg': [45, 87, 98]}

 df=pd.DataFrame(scores,index=["name1","name2","name3"])

In [243]:
df

math  eng  evg
name1    70   56   45
name2    78   67   87
name3    79   66   98

In [245]:
df1=df

In [246]:
df1

math  eng  evg
name1    70   56   45
name2    78   67   87
name3    79   66   98

In [247]:
df1.drop("name1")

math  eng  evg
name2    78   67   87
name3    79   66   98

In [248]:
df1

math  eng  evg
name1    70   56   45
name2    78   67   87
name3    79   66   98

In [259]:
df1.drop("name2",inpldace=True)

TypeError: DataFrame.drop() got an unexpected keyword argument 'inpldace'

In [260]:
df1

math  eng  evg
name2    78   67   87
name3    79   66   98

# 

In [261]:
df1.drop("math",axis=1)

eng  evg
name2   67   87
name3   66   98

In [262]:
df

math  eng  evg
name2    78   67   87
name3    79   66   98

In [263]:
df1

math  eng  evg
name2    78   67   87
name3    79   66   98

In [264]:
df.loc["name2"]

math    78
eng     67
evg     87
Name: name2, dtype: int64

In [265]:
df.set_index("eng",inplace=True)

In [266]:
df

math  evg
eng           
67     78   87
66     79   98

In [267]:
df.iloc[0,1:]

evg    87
Name: 67, dtype: int64

In [268]:
df.iloc[1,1]

98

In [271]:
df.iloc[[0,1],[1,1]]

evg  evg
eng          
67    87   87
66    98   98

In [272]:
df["lan"]=20

In [273]:
df

math  evg  lan
eng                
67     78   87   20
66     79   98   20

In [274]:
df.loc[2]=0

In [275]:
df

math  evg  lan
eng                
67     78   87   20
66     79   98   20
2       0    0    0

In [281]:
df.loc[2]=[32,10,12,23]

In [282]:
df

math  evg  lan   3
eng                    
67     78   87   20  10
66     79   98   20  12
2      32   10   12  23